import type { CatalogEntry, NormalizerCategory, NormalizerConfig, NormalizerRule, NormalizerSettings } from "@/lib/reference-normalizer/types";
import { cleanText, uniqueStrings } from "@/lib/reference-normalizer/normalization";

type RawEntry = {
  value: string;
  code: string;
  usable: boolean;
};

type RawCatalog = Record<NormalizerCategory, RawEntry[]>;

const RAW_CATALOG: RawCatalog = {
  brand: [
    { value: "ACH BRITO", code: "ACB", usable: true },
    { value: "ABC Line", code: "ABC", usable: true },
    { value: "ALGOTHERM", code: "ALG", usable: true },
    { value: "ALQVIMIA", code: "ALQ", usable: true },
    { value: "AMIMO", code: "AMI", usable: true },
    { value: "ANNE SEMONIN", code: "ASE", usable: true },
    { value: "ATELIER COLOGNE", code: "ATC", usable: true },
    { value: "AZZARO", code: "AZZ", usable: true },
    { value: "NAO USAR", code: "BEN", usable: false },
    { value: "BENAMOR - ALECRIM", code: "ALE", usable: true },
    { value: "GORDISSIMO", code: "GOR", usable: true },
    { value: "BIENVENUE", code: "BIE", usable: true },
    { value: "BALTIC BLISS", code: "BLT", usable: true },
    { value: "CASTELBEL", code: "CAS", usable: true },
    { value: "COMPAGNIE PROVENCE", code: "CDP", usable: true },
    { value: "CERERIA MOLLA", code: "CEM", usable: true },
    { value: "CHINELO", code: "CHI", usable: true },
    { value: "CAMPOS IBIZA", code: "CIB", usable: true },
    { value: "CLARINS", code: "CLA", usable: true },
    { value: "CODAGE", code: "COD", usable: true },
    { value: "CINQ MONDES", code: "CQM", usable: true },
    { value: "CABIDES", code: "CRU", usable: true },
    { value: "DAMANA", code: "DAM", usable: true },
    { value: "DAVEIA", code: "DAV", usable: true },
    { value: "DAMANA ORGANIC", code: "DOR", usable: true },
    { value: "NAO USAR", code: "EAR", usable: false },
    { value: "Exclusive Line", code: "EXC", usable: true },
    { value: "FAACE", code: "FAA", usable: true },
    { value: "FLOR DE ALGODAO", code: "FAL", usable: true },
    { value: "FLOR DOS POEMAS", code: "FDP", usable: true },
    { value: "FREDERIC MALLE - MAGNOLIA", code: "FRM", usable: true },
    { value: "EPDFM - INDELEBILE", code: "FCI", usable: true },
    { value: "ALGAE", code: "GAE", usable: true },
    { value: "GUERLAIN", code: "GUE", usable: true },
    { value: "HEIPOA", code: "HPO", usable: true },
    { value: "KEIJI", code: "KEI", usable: true },
    { value: "LARANJA VERBENA", code: "LVE", usable: true },
    { value: "Nature Line", code: "NAT", usable: true },
    { value: "NEUTROS Line", code: "NEU", usable: true },
    { value: "NKI", code: "NKI", usable: true },
    { value: "NORDIC LEISURE", code: "NLT", usable: true },
    { value: "NUXE - REVE MIEL", code: "NUX", usable: true },
    { value: "NUXE - PRESTIGE", code: "NUP", usable: true },
    { value: "OCCEAN", code: "OCC", usable: true },
    { value: "OMNISENS", code: "OMN", usable: true },
    { value: "PERRICONE", code: "PER", usable: true },
    { value: "PHYTOMER", code: "PHY", usable: true },
    { value: "PASCAL MORABITO", code: "PMO", usable: true },
    { value: "NAO USAR", code: "POC", usable: false },
    { value: "GOLD&BLUE", code: "G&B", usable: true },
    { value: "PLUM FLOWER", code: "PLF", usable: true },
    { value: "RAIZ", code: "RAI", usable: true },
    { value: "0% Plastic Line", code: "RPL", usable: true },
    { value: "NAO USAR", code: "RSB", usable: false },
    { value: "FILIGRANA", code: "FIL", usable: true },
    { value: "RUBY RED", code: "RUB", usable: true },
    { value: "SUNDARI", code: "SUN", usable: true },
    { value: "SUPORTE", code: "SUP", usable: true },
    { value: "SCANDINAVIAN WHITE", code: "SWH", usable: true },
    { value: "THE VERT", code: "THV", usable: true },
    { value: "TRUSSARDI", code: "TRU", usable: true },
    { value: "TYPOLOGY", code: "TYP", usable: true },
    { value: "USHUAIA", code: "USH", usable: true },
    { value: "VINESIME", code: "VIS", usable: true },
    { value: "WHITE TEA", code: "WHT", usable: true },
    { value: "RUSTY Line", code: "RUS", usable: true },
  ],
  format: [
    { value: "Frasco", code: "FRA", usable: true },
    { value: "Bisnaga", code: "BIS", usable: true },
    { value: "Ecopump", code: "ECP", usable: true },
    { value: "Recarga 5L", code: "REC", usable: true },
    { value: "Ghost", code: "GHT", usable: true },
    { value: "Manhattan", code: "MAN", usable: true },
    { value: "Garrafa Ecofill", code: "ECO", usable: true },
    { value: "ECOFILL", code: "ECO", usable: true },
    { value: "Recarga Ecofill", code: "ECO", usable: true },
    { value: "Recarga Ecosource", code: "ECS", usable: true },
    { value: "Solido", code: "SOL", usable: true },
    { value: "Acessorio", code: "ACE", usable: true },
    { value: "Fechado", code: "FEC", usable: true },
    { value: "Aberto", code: "ABE", usable: true },
    { value: "Havaiana", code: "HAV", usable: true },
    { value: "Saqueta", code: "SAQ", usable: true },
    { value: "Boiao", code: "BOI", usable: true },
    { value: "Stick", code: "STK", usable: true },
    { value: "Spray", code: "SPY", usable: true },
    { value: "Suporte Ecosource", code: "ECS", usable: true },
    { value: "Tampa de Ecosource", code: "ECS", usable: true },
    { value: "", code: "000", usable: true },
  ],
  product: [
    { value: "Sabonete (solido)", code: "SAB", usable: true },
    { value: "Amaciador", code: "AMA", usable: true },
    { value: "Gel Banho", code: "GBD", usable: true },
    { value: "Champo", code: "CHA", usable: true },
    { value: "Gel Maos Corpo", code: "GBD", usable: true },
    { value: "Locao de Maos e Corpo", code: "BOD", usable: true },
    { value: "Gel Corpo Cabelo", code: "GCC", usable: true },
    { value: "Sabonete Liquido", code: "SAB", usable: true },
    { value: "Champo/Amaciador", code: "CHA", usable: true },
    { value: "Body Lotion", code: "BOD", usable: true },
    { value: "Kit Dental", code: "DEN", usable: true },
    { value: "Kit Barbear", code: "BAR", usable: true },
    { value: "Touca", code: "TOU", usable: true },
    { value: "Luva Limpa Sapatos", code: "LUV", usable: true },
    { value: "Kit Vaidade", code: "VAI", usable: true },
    { value: "Cotonetes", code: "COT", usable: true },
    { value: "Discos Desmaquilhante", code: "DIS", usable: true },
    { value: "Loofah", code: "LOO", usable: true },
    { value: "Pente", code: "PEN", usable: true },
    { value: "Individual", code: "IND", usable: true },
    { value: "Duplo", code: "DUP", usable: true },
    { value: "Triplo", code: "TRI", usable: true },
    { value: "Ind. Magnetico", code: "IND", usable: true },
    { value: "Duplo Magnetico", code: "DUP", usable: true },
    { value: "SOLA EVA", code: "EVA", usable: true },
    { value: "PolyVelour", code: "PLV", usable: true },
    { value: "Balsamo", code: "BAL", usable: true },
    { value: "Sais de banho", code: "SAL", usable: true },
    { value: "Creme de maos", code: "CRM", usable: true },
    { value: "Bruma", code: "BRM", usable: true },
    { value: "Lencos de Papel", code: "LEN", usable: true },
    { value: "Lima de Unhas", code: "LIM", usable: true },
    { value: "Fio Dental", code: "FIO", usable: true },
    { value: "Saco Sanitario", code: "SCS", usable: true },
    { value: "Fosforos", code: "FOS", usable: true },
    { value: "Toalhita", code: "TAL", usable: true },
    { value: "", code: "000", usable: true },
  ],
  size: [
    { value: "30ml", code: "030", usable: true },
    { value: "30gr", code: "030", usable: true },
    { value: "400ml", code: "400", usable: true },
    { value: "300ml", code: "300", usable: true },
    { value: "375ml", code: "375", usable: true },
    { value: "100gr", code: "100", usable: true },
    { value: "500ml", code: "500", usable: true },
    { value: "20gr", code: "020", usable: true },
    { value: "25gr", code: "025", usable: true },
    { value: "40gr", code: "040", usable: true },
    { value: "40ml", code: "040", usable: true },
    { value: "50ml", code: "050", usable: true },
    { value: "60ml", code: "060", usable: true },
    { value: "80ml", code: "080", usable: true },
    { value: "Escova", code: "ESC", usable: true },
    { value: "Lamina", code: "LAM", usable: true },
    { value: "28CM", code: "028", usable: true },
    { value: "29CM", code: "029", usable: true },
    { value: "30CM", code: "030", usable: true },
    { value: "31CM", code: "031", usable: true },
    { value: "10gr", code: "010", usable: true },
    { value: "50gr", code: "050", usable: true },
    { value: "35gr", code: "035", usable: true },
    { value: "4.5ml", code: "004", usable: true },
    { value: "10ml", code: "010", usable: true },
    { value: "5LT", code: "005", usable: true },
    { value: "", code: "000", usable: true },
  ],
  packaging: [
    { value: "Caixa", code: "CXA", usable: true },
    { value: "Papel", code: "PPL", usable: true },
    { value: "Sugar Cane", code: "SGC", usable: true },
    { value: "VAZ", code: "VAZ", usable: true },
    { value: "Bolsa", code: "POU", usable: true },
    { value: "Plast. Rec.", code: "PLR", usable: true },
    { value: "BAMBU", code: "BMB", usable: true },
    { value: "STRAW", code: "STW", usable: true },
    { value: "PLASTICO", code: "PLA", usable: true },
    { value: "ABS", code: "ABS", usable: true },
    { value: "INOX", code: "INX", usable: true },
    { value: "ACO", code: "ACO", usable: true },
    { value: "", code: "000", usable: true },
  ],
  extra: [
    { value: "Branco Slim", code: "SLM", usable: true },
    { value: "Branco Classico", code: "CLS", usable: true },
    { value: "Preto Slim", code: "SLM", usable: true },
    { value: "Preto Classico", code: "CLS", usable: true },
    { value: "PLP", code: "PLP", usable: true },
    { value: "PLC", code: "PLC", usable: true },
    { value: "Slim", code: "SLM", usable: true },
    { value: "Classico", code: "CLS", usable: true },
    { value: "1.8", code: "1.8", usable: true },
    { value: "V01", code: "V01", usable: true },
    { value: "V02", code: "V02", usable: true },
    { value: "V03", code: "V03", usable: true },
    { value: "V04", code: "V04", usable: true },
    { value: "V05", code: "V05", usable: true },
    { value: "V06", code: "V06", usable: true },
    { value: "Branco", code: "BRA", usable: true },
    { value: "Preto", code: "PRT", usable: true },
    { value: "Dourado", code: "DOU", usable: true },
    { value: "Escovado", code: "ESC", usable: true },
    { value: "C019", code: "C019", usable: true },
    { value: "C024", code: "C024", usable: true },
    { value: "C026", code: "C026", usable: true },
    { value: "C028", code: "C028", usable: true },
    { value: "C030", code: "C030", usable: true },
    { value: "C036", code: "C036", usable: true },
    { value: "", code: "000", usable: true },
  ],
};

const CATEGORY_LABEL_OVERRIDES: Partial<Record<string, CatalogEntry["labels"]>> = {
  "brand:ACH BRITO": { pt: "ACB LAVANDA", es: "ACB LAVANDA", en: "ACB Lavender" },
  "brand:ALGOTHERM": { pt: "Ocean Spa", es: "Ocean Spa", en: "Ocean Spa" },
  "brand:BENAMOR - ALECRIM": { pt: "Benamor", es: "Benamor", en: "Benamor" },
  "brand:GORDISSIMO": { pt: "Benamor", es: "Benamor", en: "Benamor" },
  "brand:LARANJA VERBENA": { pt: "LARANJA-VERBENA", es: "NARANJA-VERBENA", en: "ORANGE-VERBENA" },
  "product:Amaciador": { pt: "Condicionador", es: "Acondicionador", en: "Conditioner" },
  "product:Body Lotion": { pt: "Locao Corporal", es: "Locion Corporal", en: "Body Lotion" },
  "product:Champo": { pt: "Champo", es: "Champu", en: "Shampoo" },
  "product:Gel Banho": { pt: "Gel Banho", es: "Gel Bano", en: "Shower Gel" },
  "product:Gel Corpo Cabelo": { pt: "Gel Corpo Cabelo", es: "Gel Cuerpo Cabello", en: "Hair Body Wash" },
  "product:Locao de Maos e Corpo": { pt: "Locao maos corpo", es: "Locion manos cuerpo", en: "Hand Body Lotion" },
  "product:Sabonete Liquido": { pt: "Sab Liquido", es: "Jabon liquido", en: "Liquid Soap" },
  "format:Frasco": { pt: "Frasco", es: "Frasco", en: "Bottle" },
  "format:Recarga 5L": { pt: "Recarga 5L", es: "Recarga 5L", en: "Refill 5L" },
  "packaging:VAZ": { pt: "Vazia", es: "Vacia", en: "Empty" },
};

const CATEGORY_ALIAS_OVERRIDES: Partial<Record<string, string[]>> = {
  "brand:ACH BRITO": ["ARCH BRITO", "ACH BRITO", "ACB LAVANDA"],
  "brand:ALGOTHERM": ["ALGOTHERM", "OCEAN SPA"],
  "brand:BENAMOR - ALECRIM": ["BENAMOR", "BENAMOR ALECRIM"],
  "brand:GORDISSIMO": ["GORDISSIMO", "GORDISSIMO BENAMOR"],
  "brand:CASTELBEL": ["CASTELBEL", "PINK LILY"],
  "product:Amaciador": ["CONDICIONADOR", "ACONDICIONADOR", "CONDITIONER"],
  "product:Locao de Maos e Corpo": ["LOCAO MAOS E CORPO", "LOCAO MAOS CORPO", "LOCION MANOS CUERPO", "HAND BODY LOTION"],
  "product:Sabonete Liquido": ["SABONETE LIQUIDO", "SAB LIQUIDO", "JABON LIQUIDO", "LIQUID SOAP"],
  "product:Body Lotion": ["BODY LOTION", "LOCAO CORPORAL", "LOCION CORPORAL", "LOTION CORPORELLE"],
  "product:Gel Corpo Cabelo": ["GEL CORPO E CABELO", "GEL CORPO CABELO", "HAIR BODY WASH"],
  "product:Champo": ["CHAMPO", "CHAMPOO", "SHAMPOO", "CHAMPO CASTELBEL"],
  "product:Gel Banho": ["GEL BANHO", "GEL DE BANHO", "GEL DOUCHE"],
  "product:Champo/Amaciador": ["CHAMPO CONDICIONADOR", "2 EM 1", "2IN1"],
  "packaging:Plast. Rec.": ["PLAST REC", "PLAST RECICLADO", "PLASTICO RECICLADO", "PLAST REC."],
  "packaging:VAZ": ["VAZ", "VAZIA", "VACIA", "EMPTY"],
  "format:Garrafa Ecofill": ["GARRAFA ECOFILL", "ECOFILL SLIM"],
  "format:Recarga Ecofill": ["RECARGA ECOFILL", "ECOFILL RECARGA"],
  "format:Recarga 5L": ["RECARGA 5L", "RECARGA 5LT", "5L", "5LT"],
  "format:Suporte Ecosource": ["SUPORTE ECOSOURCE", "SUP ECOSOURCE", "SUP NOVO"],
  "format:Tampa de Ecosource": ["TAMPA ECOSOURCE", "TAMPA DE ECOSOURCE"],
  "format:Recarga Ecosource": ["RECARGA ECOSOURCE", "ECOSOURCE RECARGA"],
  "format:Ecopump": ["ECOPUMP", "ECO PUMP"],
};

function defaultLabels(value: string): CatalogEntry["labels"] {
  const cleanValue = cleanText(value);
  return { pt: cleanValue, es: cleanValue, en: cleanValue };
}

function buildEntryId(category: NormalizerCategory, value: string, index: number) {
  const slug = cleanText(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || `empty-${index + 1}`;
  return `${category}-${slug}-${index + 1}`;
}

export function buildDefaultCatalogEntries(): CatalogEntry[] {
  return (Object.entries(RAW_CATALOG) as Array<[NormalizerCategory, RawEntry[]]>).flatMap(([category, items]) =>
    items.map((item, index) => {
      const key = `${category}:${item.value}`;
      const labels = CATEGORY_LABEL_OVERRIDES[key] ?? defaultLabels(item.value);
      const detectionAliases = uniqueStrings([
        item.value,
        item.code,
        labels.pt,
        labels.es,
        labels.en,
        ...(CATEGORY_ALIAS_OVERRIDES[key] ?? []),
      ]);

      return {
        id: buildEntryId(category, item.value, index),
        category,
        canonicalValue: item.value,
        code: item.code,
        usable: item.usable,
        enabled: true,
        labels,
        detectionAliases,
        notes: key === "packaging:VAZ" ? "Oculta na designacao apenas em artigos tipo garrafa." : undefined,
        metadata: {},
        sortOrder: index + 1,
      };
    }),
  );
}

export function buildDefaultRules(): NormalizerRule[] {
  return [
    {
      id: "rule-preserve-vaz-reference",
      name: "Preservar VAZ na referencia",
      description: "Mantem sempre o token VAZ na referencia final quando existe na referencia antiga.",
      enabled: true,
      priority: 10,
      stage: "reference",
      matchType: "contains",
      matchLogic: "and",
      conditions: [{ field: "oldReference", matchType: "contains", value: "VAZ" }],
      actions: [{ type: "preserveReferenceToken", token: "VAZ" }],
      source: "system",
    },
    {
      id: "rule-hide-vazia-on-bottle",
      name: "Ocultar VAZ apenas em garrafa",
      description: "Esconde Vazia/Vacia/Empty apenas quando o formato e garrafa.",
      enabled: true,
      priority: 20,
      stage: "designation",
      matchType: "exact",
      matchLogic: "and",
      conditions: [
        { field: "detectedPackaging", matchType: "exact", value: "VAZ" },
        { field: "detectedFormat", matchType: "contains", value: "Garrafa" },
      ],
      actions: [{ type: "hideLabelInDesignation", category: "packaging" }],
      source: "system",
    },
    {
      id: "rule-algotherm-ocean-spa",
      name: "ALGOTHERM -> Ocean Spa",
      description: "Usa Ocean Spa como designacao visivel.",
      enabled: true,
      priority: 30,
      stage: "designation",
      matchType: "exact",
      matchLogic: "and",
      conditions: [{ field: "detectedBrand", matchType: "exact", value: "ALGOTHERM" }],
      actions: [{ type: "setLabelTranslations", category: "brand", labels: { pt: "Ocean Spa", es: "Ocean Spa", en: "Ocean Spa" } }],
      source: "system",
    },
    {
      id: "rule-ach-brito-lavanda",
      name: "ACH BRITO -> ACB LAVANDA",
      description: "Mantem codigo canonico e troca a designacao visivel.",
      enabled: true,
      priority: 40,
      stage: "designation",
      matchType: "contains",
      matchLogic: "or",
      conditions: [
        { field: "detectedBrand", matchType: "exact", value: "ACH BRITO" },
        { field: "oldDesignation", matchType: "contains", value: "ARCH BRITO" },
      ],
      actions: [{ type: "setLabelTranslations", category: "brand", labels: { pt: "ACB LAVANDA", es: "ACB LAVANDA", en: "ACB Lavender" } }],
      source: "system",
    },
    {
      id: "rule-benamor-collapse",
      name: "Benamor / Gordissimo -> Benamor",
      description: "Reduz a marca visivel a Benamor.",
      enabled: true,
      priority: 50,
      stage: "designation",
      matchType: "contains",
      matchLogic: "or",
      conditions: [
        { field: "detectedBrand", matchType: "contains", value: "BENAMOR" },
        { field: "detectedBrand", matchType: "contains", value: "GORDISSIMO" },
      ],
      actions: [{ type: "setLabelTranslations", category: "brand", labels: { pt: "Benamor", es: "Benamor", en: "Benamor" } }],
      source: "system",
    },
    {
      id: "rule-product-amaciador",
      name: "Amaciador -> Condicionador",
      description: "Substitui os labels visiveis do produto por idioma.",
      enabled: true,
      priority: 60,
      stage: "designation",
      matchType: "exact",
      matchLogic: "and",
      conditions: [{ field: "detectedProduct", matchType: "exact", value: "Amaciador" }],
      actions: [{ type: "setLabelTranslations", category: "product", labels: { pt: "Condicionador", es: "Acondicionador", en: "Conditioner" } }],
      source: "system",
    },
    {
      id: "rule-product-hand-body",
      name: "Locao de Maos e Corpo",
      description: "Aplica labels curtos por idioma.",
      enabled: true,
      priority: 70,
      stage: "designation",
      matchType: "contains",
      matchLogic: "or",
      conditions: [
        { field: "detectedProduct", matchType: "contains", value: "Locao de Maos e Corpo" },
        { field: "oldDesignation", matchType: "contains", value: "Locao de Maos e Corpo" },
      ],
      actions: [{ type: "setLabelTranslations", category: "product", labels: { pt: "Locao maos corpo", es: "Locion manos cuerpo", en: "Hand Body Lotion" } }],
      source: "system",
    },
    {
      id: "rule-product-liquid-soap",
      name: "Sabonete Liquido",
      description: "Aplica labels curtos multilingua.",
      enabled: true,
      priority: 80,
      stage: "designation",
      matchType: "contains",
      matchLogic: "or",
      conditions: [
        { field: "detectedProduct", matchType: "contains", value: "Sabonete Liquido" },
        { field: "oldDesignation", matchType: "contains", value: "Sabonete Liquido" },
      ],
      actions: [{ type: "setLabelTranslations", category: "product", labels: { pt: "Sab Liquido", es: "Jabon liquido", en: "Liquid Soap" } }],
      source: "system",
    },
    {
      id: "rule-castelbel-special",
      name: "CASTELBEL -> Pink Lily ou variante",
      description: "Se estiver sozinho vira Pink Lily, se tiver variante mostra so a variante.",
      enabled: true,
      priority: 90,
      stage: "designation",
      matchType: "contains",
      matchLogic: "or",
      conditions: [
        { field: "detectedBrand", matchType: "exact", value: "CASTELBEL" },
        { field: "oldDesignation", matchType: "contains", value: "CASTELBEL" },
      ],
      actions: [{ type: "extractRemainderAfterBrandOrFallback", category: "brand", fallbackLabels: { pt: "Pink Lily", es: "Pink Lily", en: "Pink Lily" } }],
      source: "system",
    },
    {
      id: "rule-remove-abbreviation-dots",
      name: "Remover pontos de abreviaturas",
      description: "Remove pontos de abreviaturas sem afetar decimais.",
      enabled: true,
      priority: 100,
      stage: "designation",
      matchType: "contains",
      matchLogic: "or",
      conditions: [{ field: "designationPt", matchType: "contains", value: "." }],
      actions: [{ type: "replaceTextInDesignation", language: "all", pattern: "(?<=\\b[A-Za-z]{2,})\\.(?=\\s|$)", replacement: "", regex: true }],
      source: "system",
    },
    {
      id: "rule-tighten-hyphen-spacing",
      name: "Ajustar espacos de hifen",
      description: "Remove espacos em volta do hifen.",
      enabled: true,
      priority: 110,
      stage: "designation",
      matchType: "contains",
      matchLogic: "or",
      conditions: [{ field: "designationPt", matchType: "contains", value: "-" }],
      actions: [{ type: "replaceTextInDesignation", language: "all", pattern: "\\s*-\\s*", replacement: "-", regex: true }],
      source: "system",
    },
    {
      id: "rule-missing-brand-review",
      name: "Rever quando a marca falta",
      description: "Marca a linha para revisao quando a marca nao e identificada.",
      enabled: true,
      priority: 200,
      stage: "validation",
      matchType: "exact",
      matchLogic: "and",
      conditions: [{ field: "detectedBrand", matchType: "exact", value: "" }],
      actions: [{ type: "forceStatusReview", message: "Marca nao identificada com seguranca." }],
      source: "system",
    },
  ];
}

export const DEFAULT_NORMALIZER_SETTINGS: NormalizerSettings = {
  charLimitPt: 60,
  charLimitEs: 60,
  charLimitEn: 60,
};

export function buildDefaultNormalizerConfig(): NormalizerConfig {
  return {
    catalog: buildDefaultCatalogEntries(),
    rules: buildDefaultRules(),
    settings: DEFAULT_NORMALIZER_SETTINGS,
  };
}
